language: node_js
node_js:
- node
install:
- sudo npm install -g --unsafe-perm node-red
- npm install
before_script:
- node --version
- npm --version
after_success: npm run coverage
env:
  global:
  - NODE_ENV=test